### ISSUE TITLE
Code Snippets Title can be cut off

### ISSUE THREAD

**Issue by LordLambda** [rawcodeio/Bug-Report#10]
This is related in part to Issue #9 . 

Code snippet titles seem to be cut off when they exceed ~25 characters. Note I put the around here as it's actually dependent on the characters you use, but the basic idea is the same. I feel a cut off of 17 added by three dots for a total of 20 characters would be appropriate here. 

Devices tested on (all had this issue) (though presumably this happens in all browsers):
Mac Chrome (46)
Mac Firefox (41)
Mac Safari (9.0.1)
Windows 7 IE 10
Windows 7 IE 11
Windows 10 Microsoft Edge

[Image][imagelink] of the problem  happening.

Using your code from #9 
```
<div class="item">
      <div class="inner">
      <a href="snippets/<%= el._id %>" class="inneritem">
      <span class="<%= el.language.toLowerCase() %> lang">
        <% if(el.language != "undef"){ %>
          <%= el.language %>
        <% } %>
      </span>
        <h2><%= el.name %></h2>
        <p>
          <%= el.info.split(/\s+/,10).join(" "); %> ...
        </p>
      </a>
      </div>
    </div>
```

Specifically the:
```
<h2><%= el.name %></h2>
```
This could be modified to for example the following:
```
<h2>
  <%= el.name.length > 20 ? el.name[0..17].gsub(/\s\w+\s*$/,'...') : el.name.length%>
</h2>
```

[imagelink]: http://content.screencast.com/users/ecoan/folders/Jing/media/520e81d5-0e90-4425-b5e9-362045dd0569/00000132.png

**Comment by BenMann** [comment]
Same fix applied as explained [here](https://github.com/rawcodeio/Bug-Report/issues/9)
