### ISSUE TITLE
Descriptions save when only a newline is saved

### ISSUE THREAD

**Issue by LordLambda** [rawcodeio/Bug-Report#11]
As mentioned in #9 (First X-Post):
[...]when an image only has a newline as shown in [THIS][image] image here. Links for the individual snippets:
[Snippet 1][link1].
[Snippet 2][link2].
[Snippet 3][link3].

Perhaps we should strip new lines, and say the description is nothing when it is only new lines? I understand not wanting to cut out newlines, but maybe a check to make sure there are no characters perhaps something such as:
```
textToSave = '\n\n'
if not textToSave.blank?
```
or perhaps:
```
textToSave = '\n\n'
if not textToSave.nil? and textToSave.strip.empty?
```

[image]: http://content.screencast.com/users/ecoan/folders/Jing/media/d31dfd96-115a-40d5-9815-b230ea0a410c/00000139.png
[link1]: http://rawcode.io/snippets/NymDJXNbl/Another%20Javascript%20Test
[link2]: http://rawcode.io/snippets/VJUMHgmbl/prevent%20code%20injection%20through%20.htaccess
[link3]: http://rawcode.io/snippets/VJtWJ7V-g/Ruby%20Test

**Comment by BenMann** [comment]
Also names and descriptions shuld have no preceding whitespaces, as in this img.
![bildschirmfoto 2015-10-29 um 06 31 21](https://cloud.githubusercontent.com/assets/7561396/10810943/d303130a-7e06-11e5-8ab9-c0564bdbda71.png)
