### ISSUE TITLE
Fix broken links / Clean up DB

### ISSUE THREAD

**Issue by devariya** [rawcodeio/Bug-Report#13]
Please check this link ,it's broken http://rawcode.io/snippets/41qdAqugl/WP%20remove%20empty%20paragraph

WP remove empty paragraph

**Comment by BenMann** [comment]
Thanks for the report! :-) 
I'm afraid that is one of my own early snippets, which I broke during the first couple of days. Its status is neither public nor private. I'd like to file this under "still in beta" but I'll have to do some database-cleaning anyway. Will fix when I get there - probably end of week.

**Comment by devariya** [comment]
No Problem , Great Work Guys :)

**Comment by calendee** [comment]
Another broken link.  This worked on 10/27/2015.

http://rawcode.io/snippets/V1BA6OOZe/Absolute%20center

**Comment by BenMann** [comment]
Hey, thanks for letting me know 👍 
This might actually be a different issue! I think the snippet was deleted, as a search for "Absolute center" doesn't find it. However those cases should be handled anyway and are not right now. 

Or can you actually find the snippet / click it from somewhere?
In that case I'll have to look it up in the DB.

**Comment by calendee** [comment]
Sorry for using the same issue then.  I figured it was the same problem.

I did a search as well but did not find it.

**Comment by BenMann** [comment]
Oh no worries :-) 
I'm glad to get feedback of any kind, plus it is still a bug. Might fix and close in the same issue as well. it still fits the title: "fix broken links" =>  fix links of deleted snippets.

**Comment by BenMann** [comment]
I checked the above snippet and it's there & private.  
This and slightly enhanced error handling in https://github.com/rawcodeio/Bug-Report/issues/16
should be sufficent.  
Closing. :tada:
