### ISSUE TITLE
My Snippets Disappear After Upload 

### ISSUE THREAD

**Issue by btcrooks** [rawcodeio/Bug-Report#15]
I've uploaded about 4 bash/shell snippets which show up on the home feed and disappear ~5 minutes later.

**Comment by BenMann** [comment]
The landingpage is indeed a feed, so new snippets will push away older ones. As long as the snippets are still there in general (you profile / can be found via search) there is probably nothing wrong with it. 

Are they still visible in your profile? Dod they dissappear completely? Are they just private by accident? 
Will need a littl emore info to really help here. Snippet names would also help!

**Comment by btcrooks** [comment]
No problem, I don't remember the snippet names specifically but they disappear on my profile as well. The only thing that stays is a Vertical Centering snippet that i've never uploaded. (My username is btcrooks)

**Comment by BenMann** [comment]
@btcrooks does this still happen? (fingers crossed)

**Comment by BenMann** [comment]
Can't replicate anymore, so closing. Let me know if it persists!
