### ISSUE TITLE
Error Pages don't have a default Error Message

### ISSUE THREAD

**Issue by LordLambda** [rawcodeio/Bug-Report#16]
Error Pages don't provide a default error message. This causes Error Pages, to well run into an error.
Screenshot: [HERE][screencast]

This particular example was reached by performing the following steps:
1. Make a Private Snippet.
2. Copy the URL of the snippet
3. Sign Out of your account.
4. Attempt to access the snippet. By URL.

Two possible solutions as I see it:
1. Add in a default error message.
2. When using the 404 redirect for private snippets, include an error message by default.

[screencast]: http://i.imgur.com/X9z55B9.png

**Comment by BenMann** [comment]
I was considering this an edge case, but it nevertheless needs handling.
Just fixed it. Test: http://rawcode.io/snippets/4JhFsF7Eg/Testing
   
Thanks for reporting!
