### ISSUE TITLE
Bug in index.ejs

### ISSUE THREAD

**Issue by LordLambda** [rawcodeio/Bug-Report#2]
Went to rawcode.io on Latest FF (41), Mac OS X 10.10.5, and ran across this super sad 404 page.

Error code for reference:
```
/home/vr10172/rawcode/views/index.ejs:28 26| <h2><%= el.name %></h2> 27| <p> >> 28| <%= el.info.split(/\s+/,10).join(" "); %> ... 29| </p> 30| </a> 31| </div> Cannot call method 'split' of null 
```
Would leave a more detailed view, but I haven't taken the time to really look into the code yet, and don't have the time too so it wouldn't be of much help.

**Comment by BenMann** [comment]
Thx for the report! Fixed.
Kinda night time here, nice timing for hitting hackernews :]
