### ISSUE TITLE
Unable to view documents with special characters in title.

### ISSUE THREAD

**Issue by LordLambda** [rawcodeio/Bug-Report#3]
I noticed [THIS][link] page which seems to be giving a 404 not found even though at the time it [SHOWED][link2] on the main Page.

The reason for it showing this I believe is due to in the title it had the characters: "Abreviações". Specifically the: "çõ". I believe this to be the problem with the URL creation scheme/link lookup. Perhaps doesn't properly handle URL encoded values when doing the lookup? This would be my guess since it renders great on the main page, but is only the link to the page that's broken.

Tested on Mac OS X 10.10.5 - Latest FireFox (41)
Tested on Arch Linux (Latest) - Latest FireFox (41)

[link]:http://rawcode.io/snippets/4JkB7Nagg/Abrevia%E7%F5es
[link2]:http://content.screencast.com/users/ecoan/folders/Jing/media/1abeb884-8bd1-45fe-9335-dee574b265b6/00000125.png

**Comment by BenMann** [comment]
Thanks for the catch. URLs should be properly ecoded now. Searching for "Abreviaçones" surfaces that particular snippet and the link to it is working for me now. (FF nightly).
Can you confirm this?

**Comment by LordLambda** [comment]
Yes I can confirm. Brings it up beautifully now.
