### ISSUE TITLE
Accessing snippet from page 2 gives error

### ISSUE THREAD

**Issue by nagarjuna993** [rawcodeio/Bug-Report#4]
Accessing the snippet from the second page (snippets page 2) gives a error
`Cannot GET /snippets/page/snippets/E1Ktr1bex`
this is the link:
`http://rawcode.io/snippets/page/snippets/E1Ktr1bex`
the link to the snippet page is not getting over written, i think it has to do something with the .htaccess file.

**Comment by BenMann** [comment]
Thanks for reporting!
URL is supposed to start at the root (http://rawcode.io/snippets/E1Ktr1bex)
Will fix when I get home - less than 6h from now 😉
