### ISSUE TITLE
Snippet description text box moves when a tag is typed

### ISSUE THREAD

**Issue by Lanzafame** [rawcodeio/Bug-Report#5]
On the new snippet page the 'extra info' text box moves to the left of the screen when a tag is started to be typed into the tags field, see below:
<img width="855" alt="screen shot 2015-10-20 at 10 25 53 pm" src="https://cloud.githubusercontent.com/assets/5924712/10606958/a72aebc4-7779-11e5-9b24-a35f7399f701.png">

**Comment by BenMann** [comment]
Now that one is curious :D
Can only reproduce this on chrome so far and it self-fixes if
you resize the window. Will look into it, thanks for the report! :+1:

**Comment by BenMann** [comment]
Errmm so.. it's fixed for me, can you confirm this?
The strange thing is it was caused by this:

```
textarea{
  height: auto !important;
}
```

Either there is something really wrong with chrome, which could be investigated further, or I should have never used that ```!important```  - probably both :P

**Comment by Lanzafame** [comment]
Fixed :+1:

**Comment by BenMann** [comment]
Thank you. Awesome!
