### ISSUE TITLE
Editing snippets saves them as private by default.

### ISSUE THREAD

**Issue by nigelheap** [rawcodeio/Bug-Report#6]
After editing an old snippet it was deleted from my list and from the public one.

**Comment by BenMann** [comment]
Was it deleted completely or turned private? There was something fishy with them turning private unexpectedly. Can you give me the name of the snippet?

**Comment by nigelheap** [comment]
It didn't appear under /snippets or on the home page after editing it. I didn't mark it as private unless the select box not defaulted to the saved value on the edit form. 
If it was private it didn't appear for me to view/edit.

**Comment by BenMann** [comment]
Yeah the select might have defaulted to "private". Does the snippet show up in your profile if you switch to private snippets? Otherwise I will need more info about that snippet to reconstruct what happened!

**Comment by nigelheap** [comment]
Yes the old ones are there, sorry i didn't realise I could get to the private snippets though there. 
I guess it's just the select box defaulting to private on the edit page.

**Comment by BenMann** [comment]
Nice! Thanks a ton for letting me know. Will fix soon! 
Glad the snippet hasn't gone missing in the database ;-)

**Comment by BenMann** [comment]
And it's fixed! 
Thanks again for reporting! :+1:
