### ISSUE TITLE
Snippet paging bug

### ISSUE THREAD

**Issue by shoeyn** [rawcodeio/Bug-Report#8]
There are several blank pages e.g http://rawcode.io/snippets/page/4
Just simply clicking on see more snippets and keep clicking next will reproduce the error.
It's not just you forget to remove the next page on the last page, because http://rawcode.io/snippets/page/6 the next page button finally stops.
I'm assuming you have an approve flag to show a snippet on the front, but for the paging, it's counting all snippets

**Comment by BenMann** [comment]
Thanks for reporting. 
There is a logic that tries to get 15+1 snippets and if the +1 exists makes a new page and gets the snippets. However that seems to be broken. No idea why it stops at 6 though - will figure it out.
