### ISSUE TITLE
Code Descriptions can overlap other Code Snippets Title

### ISSUE THREAD

**Issue by LordLambda** [rawcodeio/Bug-Report#9]
# The Issue

*What is happening?*
In certain resolutions, and certain browsers it is possible for the code descriptions of certain snippets to override titles. I tested in the following browsers:
Mac Chrome (46)
Mac Firefox (41)
Mac Safari (9.0.1)
Windows 7 IE 10
Windows 7 IE 11
Windows 10 Microsoft Edge

The problem existed in:
Mac Firefox  (41) [Image][fflink]
Windows IE 11 (Not fully overlapping but could, depending on screen resolution) [Image][ielink]
Windows Edge [Image][edgelink]

This could be potentially fixed by applying padding to the snippets the link class: "inneritem" like:
```css
.inneritem {
  padding: 2px;
}
```
Note this is a really small padding, and should take some more testing, but the idea is there.

[fflink]: http://content.screencast.com/users/ecoan/folders/Jing/media/66f313d5-1524-4f98-ac5d-531e77cc6ee7/00000128.png
[ielink]: http://content.screencast.com/users/ecoan/folders/Jing/media/8b023a05-7fd2-432c-87d8-fb3d9d773770/00000129.png
[edgelink]: http://content.screencast.com/users/ecoan/folders/Jing/media/3f5b5bdc-c955-4d45-8106-9be95394a93c/00000130.png

**Comment by BenMann** [comment]
Thanks for letting me know. Should have cut the string but I guess some CSS can fix this too.
Here's how a single block looks internally. The Regex fails here: 

```
    <div class="item">
      <div class="inner">
      <a href="snippets/<%= el._id %>" class="inneritem">
      <span class="<%= el.language.toLowerCase() %> lang">
        <% if(el.language != "undef"){ %>
          <%= el.language %>
        <% } %>
      </span>
        <h2><%= el.name %></h2>
        <p>
          <%= el.info.split(/\s+/,10).join(" "); %> ...
        </p>
      </a>
      </div>
    </div>
```
I will definetely have some time on saturday/sunday and hopefully get all the issues out of the way.

**Comment by LordLambda** [comment]
This _seems_ to be the cause of not removing anything the:
```
el.info.split(/\s+/,10).join(" ");
```
Doesn't actually truncate the string, and give the first 10 results. It actually will just stop splitting. So in the case of the broken example:
```
a = "eg: <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ObvdSmPbdLg?rel=0\" frameborder=\"0\" allowfullscreen></iframe> Fix: <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ObvdSmPbdLg?rel=0&wmode=transparent\" frameborder=\"0\" allowfullscreen></iframe>"
b = a.split(/\s+/,10);
puts b
```
If you notice we'll get back: 
```["eg:", "<iframe", "width=\"560\"", "height=\"315\"", "src=\"https://www.youtube.com/embed/ObvdSmPbdLg?rel=0\"", "frameborder=\"0\"", "allowfullscreen></iframe>", "Fix:", "<iframe", "width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ObvdSmPbdLg?rel=0&wmode=transparent\" frameborder=\"0\" allowfullscreen></iframe>"]```
The split up string still has the full description. It just stops cutting the array after it's reached the 10th element in the array.

So perhaps the better way would be to do something like the following:
```
el.info.split(/\s+/).first(10).join(" ");
```
This way you split by space, and only grab the elements you need too. E.g.:
```
a = "eg: <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ObvdSmPbdLg?rel=0\" frameborder=\"0\" allowfullscreen></iframe> Fix: <iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/ObvdSmPbdLg?rel=0&wmode=transparent\" frameborder=\"0\" allowfullscreen></iframe>"
c = "test two"
b = a.split(/\s+/).first(10).join(" ");
puts b
d = c.split(/\s+/).first(10).join(" ");
puts d
```
Returns:
```
eg: <iframe width="560" height="315" src="https://www.youtube.com/embed/ObvdSmPbdLg?rel=0" frameborder="0" allowfullscreen></iframe> Fix: <iframe width="560"

test two
```

**Comment by LordLambda** [comment]
It should also be noted that with this if someone doesn't put spaces it wouldn't properly split right either. Although the chances are low someone wouldn't put spaces in it should be looked into handling those cases.

**Comment by BenMann** [comment]
Because we know at which point we want to cut off, I think it is actually better (performace-wise) to not even go with RegExp. We can just use ```substr``` and also get rid of the problem that occurs if somebody doesn't use whitespaces. 

On a side note, thanks for being awesome and providing fixes for the bugs you report ❤️

Same fix was applied to the title - as stated in [this issue](https://github.com/rawcodeio/Bug-Report/issues/10)

```
<div class="item">
      <div class="inner">
      <a href="snippets/<%= el._id %>" class="inneritem">
      <span class="<%= el.language.toLowerCase() %> lang">
        <% if(el.language != "undef"){ %>
          <%= el.language %>
        <% } %>
      </span>
        <h2><%= el.name.length > 20 ? el.name.substr(0, 17)+"..." : el.name %></h2>
        <p>
        <% if(el.info) {%>
          <%= el.info.substr(0, 80); %> ...
        <% } %>
        </p>
      </a>
      </div>
    </div>
```

**Comment by LordLambda** [comment]
Ah yeah I was just trying to keep in line with what you did, but I agree substr is probably the best fix performance wise. (Especially with the spaces containment).

Hey, no problem do what I can :smile: Just glad I can help out.

Understand the fix for the title, but (don't feel it should be made into in it's on issue, but possibly should?, feel it's more an extension of this) as for the info substring should you add a ternary/if statement for displaying the three dots? Such as with the title?
To remove three dots altogether (although it's fairly easy):
```<% if(el.info) {%>
          <%= el.info.length > 80 ? el.info.substr(0, 80) + "..." : el.info %> ...
        <% } %>``` (This would make info lengths that aren't to long not have the dots to imply more ([CURRENTLY][currentimage]) ([WITHOUT][withoutimage])). 

[currentimage]: http://content.screencast.com/users/ecoan/folders/Jing/media/b112a06c-5552-4bb1-9c6f-e24259e1cb28/00000137.png
[withoutimage]: http://content.screencast.com/users/ecoan/folders/Jing/media/4a6e17b3-f543-486d-81f7-17ebdf91d6b8/00000138.png

**Comment by LordLambda** [comment]
This could also fix when an image only has a newline as shown in [THIS][image] image here. Links for the individual snippets:
[Snippet 1][link1].
[Snippet 2][link2].
[Snippet 3][link3].

There should also most likely be not saving text when it is only new lines (new issue perhaps? Will file new issue for that).

[image]: http://content.screencast.com/users/ecoan/folders/Jing/media/d31dfd96-115a-40d5-9815-b230ea0a410c/00000139.png
[link1]: http://rawcode.io/snippets/NymDJXNbl/Another%20Javascript%20Test
[link2]: http://rawcode.io/snippets/VJUMHgmbl/prevent%20code%20injection%20through%20.htaccess
[link3]: http://rawcode.io/snippets/VJtWJ7V-g/Ruby%20Test

**Comment by BenMann** [comment]
I like that! Especially not displaying the dots in case no description was provided. I will also add a tag/language for sippets that don' have one assigned. So if you don't set a specific language, it will still show a default tag (like CSS, JavaScript) etc. in front of the title. Currently not providing a language makes it look a little strange. 

So anyay.. this is what the description looks like now:  
```
<% if(el.info) {%>
    <%= el.info.length > 80 ? el.info.substr(0, 80) + "..." : el.info %>
<% } %>
```
